AWSTemplateFormatVersion: 2010-09-09
Resources:
  ASG:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones:
        - us-east-1a
      MaxSize: '2'
      MinSize: '2'
      LaunchConfigurationName: !Ref LC
  LC:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: ami-0de53d8956e8dcf80
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroup
  SecurityGroup:
    Description: Security group configured for ssh and http access
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group For EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0