AWSTemplateFormatVersion: 2010-09-09
Resources:
  ASG:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones:
        - us-east-1a
      MaxSize: '2'
      MinSize: '2'
      InstanceId: !Ref EC2Instance
  EC2Instance:
    Description: EC2 Linux AMI
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: "ami-0de53d8956e8dcf80" #This is a Linux AMI
      InstanceType: t2.micro
      KeyName: rgederin-aws-key-pair
      SecurityGroups:
        - !Ref SecurityGroup
  SecurityGroup:
    Description: Security group configured for ssh and http access
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group For EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  PublicIp:
    Description: EC2Instance public IP
    Value: !GetAtt EC2Instance.PublicIp
