# create-stack --stack-name week0 --template-body file:///Users/rgederin/github/aws-sandbox/cloudformation/week-0-ec2.cfn.yml --parameters ParameterKey=InstanceType,ParameterValue=t2.micro

# aws cloudformation describe-stacks --stack-name week0

# aws cloudformation delete-stack --stack-name week0

Description: A template for creating EC2 instance

Parameters:
  InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08d9a394ac1c2994c
      InstanceType:
        Ref: InstanceType

Outputs:
  PublicIp:
    Description: EC2Instance public IP
    Value: !GetAtt EC2Instance.PublicIp
