# aws cloudformation create-stack --stack-name week0 --template-body file:///{full path to the cloudformation file}/week-0-ec2.cfn.yml

# aws cloudformation describe-stacks --stack-name week0

# aws cloudformation delete-stack --stack-name week0

Description: A template for creating EC2 instance

Parameters:
  EC2InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  EC2InstanceAmiId:
    Description: AMI identifier for the EC2 instance
    Type: String
    Default: ami-08d9a394ac1c2994c

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2InstanceAmiId
      InstanceType: !Ref EC2InstanceType

Outputs:
  PublicIp:
    Description: EC2 Instance public IP
    Value: !GetAtt EC2Instance.PublicIp
