AWSTemplateFormatVersion: "2010-09-09"
Description: A template for creating EC2 instance with security group configured with ssh and http access
Resources:
  EC2Instance:
    Description: EC2 Linux AMI
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0a887e401f7654935" #This is a Linux AMI
      InstanceType: t2.micro
      KeyName: rgederin-aws-key-pair
      SecurityGroups:
        - !Ref SecurityGroup
  SecurityGroup:
      Description: Security group configured for ssh and http access
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Security Group For EC2
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
Outputs:
  PublicIp:
    Description: EC2Instance public IP
    Value: !GetAtt EC2Instance.PublicIp
